### ISSUE TITLE
Reason for using PermissiveGestureRecognizerDelegate by default?

### ISSUE THREAD

**Issue by devxoul** [RxSwiftCommunity/RxGesture#42]
### Question

RxGesture uses `PermissiveGestureRecognizerDelegate` by default in [View+RxGesture.swift#L92](https://github.com/RxSwiftCommunity/RxGesture/blob/1.0.0/Pod/Classes/View%2BRxGesture.swift#L92). Is there any reason to use this by default?

### Background

1. I used `tapGesture()` in the subview of `UICollectionViewCell`.
2. Start scrolling the collection view.
3. Tap collection view to stop scrolling.
4. Unwanted `tapGesture()` is fired. 😱
5. To prevent this, I have to create such like `ExclusiveGestureRecognizerDelegate` and pass it to configuration closure.
6. Why do we need `PermissiveGestureRecognizerDelegate` by default? 🤔

### Possible Actions

If `PermissiveGestureRecognizerDelegate` is necessary, I think we could take these actions:

1. :warning: Let users recognize that `PermissiveGestureRecognizerDelegate` is set by default.
2. Provide such like `defaultGestureRecognizerDelegate` to give an opportunity to set default delegate.
3. Anything else?

---

And thanks for creating this cool library! :tada:

**Comment by jegnux** [comment]
> RxGesture uses `PermissiveGestureRecognizerDelegate` by default in [View+RxGesture.swift#L92](https://github.com/RxSwiftCommunity/RxGesture/blob/1.0.0/Pod/Classes/View%2BRxGesture.swift#L92). Is there any reason to use this by default?

This delegate is here for an easier use of `anyGesture()` operator allowing to attach multiple gestures at once. In that case they should be recognized simulteanously.

> To prevent this, I have to create such like `ExclusiveGestureRecognizerDelegate` and pass it to configuration closure.

This is exactly what the `configuration` closure is for :+1:

> Provide such like `defaultGestureRecognizerDelegate` to give an opportunity to set default delegate.

The problem is that if you use another third 3rd library that also uses `RxGesture`, and if you change the default delegate for the whole `RxGesture` library, it can lead to bugs in the 3rd party library relying on the default delegate.

Maybe I can add a system to `push/pop` a delegate locally: 
```swift
RxGesture.pushDefaultDelegate(ExclusiveGestureRecognizerDelegate.shared)
_ = myView.tapGesture().subscribe(onNext: { ... }) // Use ExclusiveGestureRecognizerDelegate
RxGesture.popDefaultDelegate()
```
But it's a really uncommon pattern for this use case so I don't think it's a great idea (and it's more verbose than the `configuration` solution).

The must you can do is to create free functions for configuration (you can even compose them with a `+` operator :
```swift
func + <I> (lhs: @escaping (I) -> Void, rhs: @escaping (I) -> Void) -> ((I) -> Void) {
    return  {
        lhs($0)
        rhs($0)
    }
}

func useExclusiveDelegate(_ gesture: UIGestureRecognizer) {
    gesture.delegate = ExclusiveGestureRecognizerDelegate.shared
}

func requireTableViewPanFail(_ gesture: UIGestureRecognizer) {
    gesture.require(toFail: tableView.panGestureRecognizer)
}

_ = myView.rx
    .tapGesture(configuration: useExclusiveDelegate + requireTableViewPanFail)
    .when(.recognized)
    .subscribe(onNext: { _ in
        print("did tap")
    })
```

@devxoul I let you close this issue if my answer is enough. Otherwise, feel free to suggest new solutions.

**Comment by devxoul** [comment]
That makes sense. Thanks for your detailed explanation!
